version: "3"

services:
   mongodb:
      image: mongo:latest
      container_name: CODE_CRAFT_MONGO
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: mondoDB
         MONGO_INITDB_ROOT_PASSWORD: password
         MONGO_INITDB_DATABASE: CODE_CRAFT_DB
      ports:
         - "27017:27017"
      volumes:
         - mongodb-data:/data/db

   express-app:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: CODE_CRAFT
      working_dir: /app
      volumes:
         - ./app:/app
      ports:
         - "5000:5000"
      environment:
         MONGO_INITDB_ROOT_USERNAME: mondoDB
         MONGO_INITDB_ROOT_PASSWORD: password
         MONGO_INITDB_DATABASE: CODE_CRAFT_DB
      command: npm start
      depends_on:
         - mongodb

volumes:
   mongodb-data:
